//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITler_Ein_mal_Eins {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errorcodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errorcodes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITler_Ein_mal_Eins.Errorcodes", typeof(Errorcodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabe ist ungültig.
        ///
        ///Weitere Informationen finden Sie unter dem Tab &quot;Eingabehilfe&quot;. ähnelt.
        /// </summary>
        public static string ERROR_INVALIDINPUT {
            get {
                return ResourceManager.GetString("ERROR_INVALIDINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene IPv4-Adresse ist ungültig.
        ///
        ///Weitere Informationen finden Sie unter dem Tab &quot;Eingabehilfe&quot;. ähnelt.
        /// </summary>
        public static string ERROR_IPV4DIGITISNOTVALID {
            get {
                return ResourceManager.GetString("ERROR_IPV4DIGITISNOTVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurden mehrere Felder bei einer Einzelfeldauswahl befüllt. Bitte befüllen Sie nur ein Feld. Die restlichen Felder werden automatisch befüllt. ähnelt.
        /// </summary>
        public static string ERROR_MULTIPLEFIELDSFILLED {
            get {
                return ResourceManager.GetString("ERROR_MULTIPLEFIELDSFILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Subnetzmaske ist ungültig.
        ///
        ///Weitere Informationen finden Sie unter dem Tab &quot;Eingabehilfe&quot;. ähnelt.
        /// </summary>
        public static string ERROR_SUBNETMASKISNOTVALID {
            get {
                return ResourceManager.GetString("ERROR_SUBNETMASKISNOTVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Eingaben korrekt. ähnelt.
        /// </summary>
        public static string NOERROR {
            get {
                return ResourceManager.GetString("NOERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte füllen Sie ein einzelnes Feld mit einem zulässigen, numerischen Wert.
        ///
        ///Weitere Informationen finden Sie unter dem Tab &quot;Eingabehilfe&quot;. ähnelt.
        /// </summary>
        public static string UNITC_BITS_NO_VALID_INPUT {
            get {
                return ResourceManager.GetString("UNITC_BITS_NO_VALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Einheiten-Rechner kann den eingegebenen Wertebereich leider nicht verarbeiten. 
        ///Bitte wählen Sie den Wert kleiner. ähnelt.
        /// </summary>
        public static string UNITC_BITS_RANGE_EXCEPTION {
            get {
                return ResourceManager.GetString("UNITC_BITS_RANGE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte füllen Sie ein einzelnes Feld mit einem zulässigen, numerischen Wert.
        ///
        ///Weitere Informationen finden Sie unter dem Tab &quot;Eingabehilfe&quot;. ähnelt.
        /// </summary>
        public static string UNITC_SYSTEMS_NO_VALID_INPUT {
            get {
                return ResourceManager.GetString("UNITC_SYSTEMS_NO_VALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der eingegebene Wert ist zu groß für für den gewählten Datentyp.
        ///Bitte wählen Sie den Wert passend zu dem Datentyp. ähnelt.
        /// </summary>
        public static string UNITC_SYSTEMS_RANGE_EXCEPTION {
            get {
                return ResourceManager.GetString("UNITC_SYSTEMS_RANGE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System-Fehler: Es wurde ein falscher Datentyp angegeben. Erwartet wird {0}, gesetzt wurde {1}. ähnelt.
        /// </summary>
        public static string WRONGTYPE_ERRORMESSAGE {
            get {
                return ResourceManager.GetString("WRONGTYPE_ERRORMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System-Fehler: Es wurde ein falscher Datentyp übergeben. ähnelt.
        /// </summary>
        public static string WRONGTYPE_HEADER {
            get {
                return ResourceManager.GetString("WRONGTYPE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System-Fehler: Es wurde ein falscher Datentyp übergeben. ähnelt.
        /// </summary>
        public static string WRONGTYPE_SINGLE {
            get {
                return ResourceManager.GetString("WRONGTYPE_SINGLE", resourceCulture);
            }
        }
    }
}
